### ISSUE TITLE
Do not automatically cast scalar types in "strict" mode

### ISSUE THREAD

**Issue by template-provider** [JsonMapper/JsonMapper#101]
It should be possible to throw an exception with incorrect scalar type casting.

Currently the scalar type casting is automatically depending on typed properties|doc block

```
public int $counter;
```
If the json returns a string, and not a number an exception should/could be thrown

I like a strict type mapping and not an automatically casting of the values.
For Implementing a REST API and json mapping it is easier to see a possible response problem at once (false return type).
A Feature with a strict mode casting would be nice.

**Comment by DannyvdSluijs** [comment]
Welcome @template-provider and thanks for taking the opportunity to report an issue for adding support for strict type casting.

Would you be creating a PR for this?  Or can anyone pick this up as they see fit?

A consideration I'm having is to make this available using configuration or feature flag to avoid current implementations to break on trivial type casting (e.g. casting string "12" to int 12) which was my intended goal. However I can see the opposite side here and will working on your local development you might want some stricter type casting. We should also consider union types where only after all specified types have bene tried without result throw an exception.

**Comment by template-provider** [comment]
hi,
my workload is currently huge, but if I got some time, I will dig into it.
But that will take some time.
If you can do this in the meantime, that would be great.

A configuration parameter is imho the best choice.
As far as I can see now, the ScalarType Class is created directly, so if we can do that over the factory we can use a StrictScalarType ... or something like that.
