### ISSUE TITLE
JsonMapper does not lookup Class Name correctly in array Mapping

### ISSUE THREAD

**Issue by jg-development** [JsonMapper/JsonMapper#102]
**Describe the bug**
I have a attributecollection and inside a class variable $items with Attribute[].
The json mapper should map the attribute with the same namespace, but instead lookup for another Attribute class.
The only workaround is to add the full namespace in the phpdoc.

**To Reproduce**
```php
<?php

declare(strict_types = 1);

namespace Client\Attributes;

class AttributeCollection
{
    /** @var \Client\Attribute[] */
    public array $items = [];
}

```

```php
<?php

declare(strict_types = 1);

namespace Client\Attributes;

class Attribute
{
    public string $key;
}
```

It works without the phpdoc @var attribute and full phpdoc " /** @var \Client\Attribute[] */"
but not with:  /** @var Attribute[] */ (The Collection and the attribute are in the same namespace)
I think the json mapper does not look for a class in the same namespace before looking globally.

**Comment by DannyvdSluijs** [comment]
@jg-development Thanks for taking the time to report the bug. Could you also share the JsonMapper setup? As the behavior can differ depending on the middleware used and the respective order.

**Comment by jg-development** [comment]
@DannyvdSluijs .... of course .... PHP 7.4 with the bestFit
```php
(new JsonMapperFactory())->bestFit()
```

**Comment by DannyvdSluijs** [comment]
Solved in #103 will release a new version later today

**Comment by jg-development** [comment]
thx

**Comment by DannyvdSluijs** [comment]
Version 2.7.0 was released just now. Enjoy!
