### ISSUE TITLE
Question: How to map dynamic properties?

### ISSUE THREAD

**Issue by template-provider** [JsonMapper/JsonMapper#108]
I want to build a client for the partnerize brands api: (campaigns endpoint here)
https://api-docs.partnerize.com/brand/#tag/Campaigns

The response of the "campaign_languages" can in real be not existing, emtpy string, null or an object of key values like:
```json
                "campaign_languages": {
                    "en_us": {
                        "destination_url": "https:\/\/www.foo.com
                    }
                }
```
My phpdoc looks like this:
```php
    /** @var null|string|string[] */
    public $campaign_languages;
```
My Problem is that the key "en_us" and "destination_url" are dynamic and can be "de_de" "source_url" or whatever.
Do you have any ideas how to map this into a object structure or dynamic?

**Comment by template-provider** [comment]
Hi,
I used stdClass, which was OK, but if I used a class from stdClass it does not work.
Like:
```php
class Term extends \stdClass
{
}
```

Should that be working by default?

**Comment by DannyvdSluijs** [comment]
Closing for now, feel free to reopen if more help is needed. You could also open a [discussion](https://github.com/JsonMapper/JsonMapper/discussions) as it doesn't seem to be an issue with JsonMapper

**Comment by template-provider** [comment]
I used a stdclass, which worked so for me it is not ideal but managable. It is ok for me to close it.
