### ISSUE TITLE
PropertyMapper cannot map with array in phpdoc

### ISSUE THREAD

**Issue by template-provider** [JsonMapper/JsonMapper#120]
**Describe the bug**
I have a property like this:
```php```
    /** @var string|string[] */
    public $value;
```php```

The PropertyMapper in line 160 (v. 2.9.1) uses only the first match (in this case string) for scalar mapping.
If I have a valid empty array the PropertyMapper in line 225 calls the scalarcaster and throws an error.

I use "(new JsonMapperFactory())->bestFit()" with PHP 7.4

**Comment by DannyvdSluijs** [comment]
Thanks for the detailed info and taking the time to report the bug.

I can see how this is an issue in the [PropertyMapper](https://github.com/JsonMapper/JsonMapper/blob/develop/src/Handler/PropertyMapper.php#L143). It seems the later checks for single (scalar) value does not look at the value to see if it was an array and as a result eagerly assumes the first type (single string) is correct and applies a cast to string.

Would be able to create a PR with a unit test that shows the bug and a fix for the problem?

I could take a look but I'm running a bit behind on other things so it might take some time to get this fixed.

Alternatively as a (quick and dirty) workaround you could swap the phpdoc type declaration to `string[]|string` this might doe the trick in order for you to continue.

**Comment by template-provider** [comment]
hi @DannyvdSluijs 
for the current project I did of course the "switch". My php-cs-fixer is reverting it everytime ;-), so I was searching for a permanent solution.

I will see if I have some time to add at least a unit test for this bugfix
