### ISSUE TITLE
Making own middleware - a bit unclear how to do so…

### ISSUE THREAD

**Issue by alexkuc** [JsonMapper/JsonMapper#133]
It is possible to figure out how to make your own middleware looking at [existing ones](https://github.com/JsonMapper/JsonMapper/tree/0e1b28b1bef51d1d1182c309441edfd96b95bfad/src/Middleware).

But it is not clear why [AbstractMiddleware](https://github.com/JsonMapper/JsonMapper/blob/0e1b28b1bef51d1d1182c309441edfd96b95bfad/src/Middleware/AbstractMiddleware.php) is used as a base class in some cases and in others I can see interfaces are used like [MiddlewareInterface](https://github.com/JsonMapper/JsonMapper/blob/0e1b28b1bef51d1d1182c309441edfd96b95bfad/src/Middleware/MiddlewareInterface.php) and [MiddlewareLogicInterface](https://github.com/JsonMapper/JsonMapper/blob/0e1b28b1bef51d1d1182c309441edfd96b95bfad/src/Middleware/MiddlewareLogicInterface.php).

| Middleware | "Base" |
| :--- | :--- |
| AbstractMiddleware | MiddlewareInterface, MiddlewareLogicInterface |
| CaseConversion | AbstractMiddleware |
| Debugger | AbstractMiddleware |
| DocBlockAnnotations | AbstractMiddleware |
| FinalCallback | MiddlewareInterface |
| NamespaceResolver | AbstractMiddleware |
| TypedProperties | AbstractMiddleware |
| AbstractMiddleware | AbstractMiddleware |

Maybe if there was a dedicated docs page on how to _start_ on building your own middleware it would help?
Just a few pointers as a starter, e.g. 

- to get started writing your own middleware, use xyz
- for more details, look into existing middleware and e.g. link to source code

**Comment by DannyvdSluijs** [comment]
Thanks for you input @alexkuc given you looking for answers I guess making the PR will be difficult. I’ll see when I have time available to sort it. Any specific question that is blocking you now?

**Comment by alexkuc** [comment]
@DannyvdSluijs thank you for the fast response. I am currently going over source code of the existing middleware. I'll let you know if I get stuck with something. Thank you again.

**Comment by alexkuc** [comment]
@DannyvdSluijs I managed to put something myself together. I think I got the general gist of the approach. Would you be open to PR to update docs?

**Comment by DannyvdSluijs** [comment]
PR are more than welcome. That is the power of open source.

**Comment by alexkuc** [comment]
@DannyvdSluijs I was about to start writing new README page but I just realised something so wanted to double check with you:

https://github.com/JsonMapper/JsonMapper/blob/54ac9f7b1d21c54d934ab288189752d6f9f02194/src/JsonMapperInterface.php#L11

As far as I can tell `JsonMapperInterface` does not really enforce middleware type, it's purely by convention that middleware should use `MiddlewareInterface` and `MiddlewareLogicInterface`?

**Comment by DannyvdSluijs** [comment]
@alexkuc I wanted to check with you if you still need any help, either in understanding JsonMapper or in opening a PR?

**Comment by alexkuc** [comment]
@DannyvdSluijs all is good
