### ISSUE TITLE
Add Support for Enums

### ISSUE THREAD

**Issue by Harrald** [JsonMapper/JsonMapper#172]
It would be awesome it JsonMapper could support php 8.1 Enums.

```json
'{"price": 120.0, "name": "whatever", "gender": "male"}'
```

```php
enum GenderEnum: string
{
    case MALE = 'male';
    case FEMALE = 'female';
    case OTHER = 'other';
}
```

```php
class Shoe
{
    public float $price;
    public string $name;
    public GenderEnum $gender;
}
```

**Comment by DannyvdSluijs** [comment]
Hi @Harrald 

enums are already supported, see https://github.com/JsonMapper/JsonMapper/issues/93

Any problem you’re running into, I could help with?

**Comment by Harrald** [comment]
Oh I'm sorry. In searched for it on the website and looked for a middleware. When i did not find anything i thought it was missing. 

Then this can be closed :)

**Comment by DannyvdSluijs** [comment]
Still thanks for reporting this. Now I understand this information is missing on the JsonMapper website.

**Comment by Cluster2a** [comment]
@DannyvdSluijs the documentation is still missing.
Also the rest of it seems to be outdated, as the examples use `mapObjectFromString`which is not existent anymore.

**Comment by DannyvdSluijs** [comment]
@Cluster2a thanks for the reminder. I've taken the liberty to create an issue and in the documentation repository and I'm working on it right now. You mentioned the `mapObjectFromString` is used which no longer exists. But this is very much still part of the interface, can you explain more in depth what you're running into?

**Comment by Cluster2a** [comment]
@DannyvdSluijs, for some reason I was using the verion `0.3.0` - prophably a dependency issue. Sorry - my fault.

**Comment by DannyvdSluijs** [comment]
@Cluster2a no worries. Wasn't to difficult to very on my side, and also I triggered me to resolve https://github.com/JsonMapper/jsonmapper.github.io/issues/33 so now you can copy the code examples from the website.
