### ISSUE TITLE
Add a middleware to utilise the PHP 8 Attribute

### ISSUE THREAD

**Issue by DannyvdSluijs** [JsonMapper/JsonMapper#33]
In order to help easy the mapping JsonMapper should utilise the PHP 8 Attribute options (See https://wiki.php.net/rfc/attributes_v2#alternative_syntaxwhy_not_use_or_like_other_languages)
It should introduce a middleware that processes the Attribute feature go php

The original RFC is tracked [here](https://wiki.php.net/rfc/attributes_v2)

**Comment by ssatz** [comment]
Great! I am looking for this, this way we can add validation to the property.
