### ISSUE TITLE
Migrate CI to Github Actions

### ISSUE THREAD

**Issue by DannyvdSluijs** [JsonMapper/JsonMapper#48]
Let's migrate from Travis to Github to reduce on additional services. Ideally the same matrix and steps from Travis are migrated to Github Actions.

**Comment by lambstream** [comment]
Hey Danny I'm working on this at the moment.

Could you asign this to me?

**Comment by lambstream** [comment]
Could you add the hacktoberfest topic to the repo? 
At the moment is seems to be ineligible.

**Comment by DannyvdSluijs** [comment]
Solved with #49
