### ISSUE TITLE
Badges for License, PHP version and packages are wrong

### ISSUE THREAD

**Issue by DannyvdSluijs** [JsonMapper/JsonMapper#50]
**Describe the bug**
Badges for License, PHP version and packages are wrong. All of them link to the the badge image instead of something logical or no link at all.

**To Reproduce**
1. Click on the mentioned badges on https://github.com/JsonMapper/JsonMapper and see the badge image being opened in a new tab.

**Expected behavior**
The packages badge should open https://packagist.org/packages/json-mapper/json-mapper. The license badge should open https://choosealicense.com/licenses/mit/ and the PHP badge can be without a link.

**Environment (please complete the following information):**
N/A
 
**Additional context**
N/A

**Comment by paresh27** [comment]
@DannyvdSluijs  Can you assign it to me?

**Comment by paresh27** [comment]
@DannyvdSluijs , I have generated a PR for the above issue, can you check and let me know if its good?

**Comment by DannyvdSluijs** [comment]
I’m planning to give it a review this week.  I’ll make sure you are okay for Hacktoberfest.

**Comment by DannyvdSluijs** [comment]
Resolved with #51
