### ISSUE TITLE
What are pros and cons of using this lib instead symfony/serializer?

### ISSUE THREAD

**Issue by TeroBlaZe** [JsonMapper/JsonMapper#80]
I'm just curious.
The same goal, less functionality, more simplicity and that's it?

**Comment by DannyvdSluijs** [comment]
Hi @TeroBlaZe 

I guess the pro's and con's are subjective and depend per project/person.
In the end both libs get the job done. This JsonMapper has been the result of a personal itch combined with the JsonMapper I had been using which wasn't doing the job for me. And secondly an employer that is allowing me to work
during working hours on Open Source Software which I've used to discover what is needed besides coding to publish OSS.
There is a [blog](https://infi.nl/nieuws/launching-free-open-source-software/) on the learnings.

JsonMapper offers a middleware approach that can easily be extended to fit your needs, this is one of the differences with symfony/serializer. There is already some creative middleware such as the [FinalCallback](https://github.com/JsonMapper/JsonMapper/blob/develop/src/Middleware/FinalCallback.php), [Debug](https://github.com/JsonMapper/JsonMapper/blob/develop/src/Middleware/Debugger.php) or [Eloquent](https://github.com/JsonMapper/EloquentMiddleware/blob/develop/src/EloquentMiddleware.php).

Hope this answers your questions?

**Comment by TeroBlaZe** [comment]
@DannyvdSluijs Hey! Yes, thank you. Now I get the point. Great inspiring article! It gave me some new ideas :)
Do you plan to do performance testing? I think it could help to find ways of improvements in future.

**Comment by DannyvdSluijs** [comment]
@TeroBlaZe 

Didn't plan any performance testing yet. Perhaps you have some ideas as you brought up the topic? Or some examples on how to run performance testing. I've done some in the past using val/calgrind but I expect this to have evolved over time.

**Comment by TeroBlaZe** [comment]
@DannyvdSluijs It's ok. Well, as I know there are couple well known ways to profile a php app. Xdebug and xhprof. It would be interesting to see results of memory consumption and parsing time of large json in comparison to similar libs.

**Comment by DannyvdSluijs** [comment]
I'll keep eye out for any future enhancements but will close this issue for now. Please feel free to reopen if you need to or in case of any additional questions.
