### ISSUE TITLE
Improve caching

### ISSUE THREAD

**Issue by TeroBlaZe** [JsonMapper/JsonMapper#94]
Hi!

I might did it wrong way but this drastically improves parsing speed on my system (from 16s to 6s on 36MB json file with nested objects)!!!
```php
$cache = new ArrayCache();
$mapper = (new JsonMapperFactory())->create(
    new PropertyMapper(),
    new DocBlockAnnotations($cache),
    new TypedProperties($cache),
    new NamespaceResolver($cache)

);
```
than this `(new JsonMapperFactory())->bestFit()`

It is slow because of individual cache object is used per middleware instead of shared one.

https://github.com/JsonMapper/JsonMapper/blob/97e4c6b6f5df2f1943e51cc8c76dbf1b58d84711/src/JsonMapperBuilder.php#L85-L98

May it be better to use a shared cache?

**Comment by TeroBlaZe** [comment]
Well, that was the rushed conclusion I guess. I didn't noticed a major problem there. Some props are missing when you do so. What an "improvement" hahaha.

**Comment by DannyvdSluijs** [comment]
I think you onto something though. It at the least shows a person could easily get confused. I guess  ensuring the cache can be shared should be fixed. As this is also suggested by the JsonMapperBuilder. 

I’ve re-openend this issue and will hopefully take a look somewhere this or next week.
